NoteApp/Models/ErrorViewModel.cs
namespace NoteApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NoteApp/Models/Note.cs
using System.ComponentModel.DataAnnotations;

namespace NoteApp.Models
{
    public class Note
    {

        [Key]
        public int NoteId { get; set; }

        public string? NoteName { get; set; }

        public int? NoteSubId { get; set; }

        public bool IsActive { get; set; } = true;
    }
}

NoteApp/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using NoteApp.Data;
using NoteApp.Models;
using NoteApp.Service;

namespace NoteApp.Controllers
{
    public class NoteController : Controller
    {
        private readonly INoteService _noteService;

        public NoteController(INoteService noteService)
        {
            _noteService = noteService;
        }
        public IActionResult Index(int id)
        {
          
            return View(_noteService.GetAllNote(id));
         
        }
        public IActionResult AddNote(int id)
        {
            
            var note = new Note();
            if (id != 0)
            {
                note.NoteSubId = id;
            }

            return View(note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNote(Note note)
        {
            _noteService.CreateNote(note);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _noteService.DeleteNote(id);
         
            return RedirectToAction("Index");
        }
    }
}

NoteApp/Views/Note/AddNote.cshtml
@model NoteApp.Models.Note
@{
    ViewData["Title"] = "AddNote";
}


<form method="post" asp-action="AddNote">
 <div class="container p-3">
    <div class="row pt-4">
        <div class="col-6 ">
            <div class="h4 pb-2 mb-4 text-dark border-bottom border-dark">
                Add Note
            </div>
        </div>
        <div class ="col-6 text-end">
            <input type="submit" class="btn btn-dark" value="Create"/>
        </div>
    </div>
    <div class="row pt-4">
        <div class="form-floating">
            <input asp-for="NoteName" class="form-control border-dark" placeholder="" style="height: 100px"/>
        </div>
            @if (Model.NoteSubId != 0)
            {
                @Html.Hidden("NoteSubId", Model.NoteSubId)
            }
    </div>    
  
  </div>

</form>

NoteApp/Views/Note/Index.cshtml
@model IEnumerable<Note>
@{
    ViewData["Title"] = "Notes";
}

<div class="container p-3">
 <div class="row">
    <div class="col-6 ">
       <div class="h4 pb-2 mb-4 text-dark border-bottom border-dark">
                Notes
       </div>
    </div>
    <div class="col-6 text-end">
        <a asp-controller="Note" asp-action="AddNote" class="btn btn-dark">Add new note</a>
    </div>
    <div>
      @if (Model.Count() > 0)
      {
         <table class="table table-bordered border-dark" style="width:100%">
              <tbody>
                 @foreach (var item in Model)
                 {
                   <tr>
                      <td width="85%">@item.NoteName</td>
                        <td class="text-center">
                           <a asp-controller="Note" asp-action="Index" asp-route-id="@item.NoteId" class="btn btn-info w-100">SubNotes</a>
                        </td>
                        <td class="text-center">
                           <a asp-controller="Note" asp-action="AddNote" asp-route-id="@item.NoteId" class="btn btn-warning w-100">Add</a>
                        </td>
                        <td class="text-center">
                           <a asp-controller="Note" asp-action="Delete" asp-route-id="@item.NoteId" class="btn btn-danger w-100">Delete</a>
                        </td>
                   </tr>
                 }
              </tbody>
         </table>
      }
      else
      {
         <p>No items created yet</p>

      }
    </div>
 </div>
</div>

NoteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NoteApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NoteApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NoteApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NoteApp 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>